movie_base/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_module_1.urls')),
]

movie_module_1/urls.py
from django.urls import  path
from django.conf.urls.static import static
from django.conf import settings
from .views import add_movie, delete_me, home_view,get_movie, update
app_name='module1'
urlpatterns=[
    path('',home_view,name='home'),
    path('movie/<int:movie_id>/',get_movie,name='search'),
    path('register',add_movie,name='add_movie'),
    path('edit/<int:id>/',update,name='edit'),
    path('delete/<int:id>/',delete_me,name='delete'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie_module_1/models.py
from django.db import models

# Create your models here.
class Details(models.Model):
    name=models.CharField(max_length=200)
    title=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='uploads')
    img.blank=True

movie_module_1/forms.py
from django import forms
from django.db.models.fields import TextField
from django.forms.widgets import FileInput, TextInput
from .models import Details

class edit_form(forms.ModelForm):
    class Meta:
        model=Details
        fields=['name','title','year','img']
        widgets={
            'name':TextInput(attrs={'class':'form-control'}),
            'title':TextInput(attrs={'class':'form-control'}),
            'year':TextInput(attrs={'class':'form-control'}),
            'img':FileInput(attrs={'class':'form-control'}),
        }
        

movie_module_1/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import Details
from .forms import edit_form
# Create your views here.

# Home Page
def home_view(req):
    get_content=Details.objects.all()
    return render(req,'home.html',{'data':get_content})

# Fetch movie details individually
def get_movie(req,movie_id):
    get_data=Details.objects.get(id=movie_id)
    return render(req,'details.html',{'data':get_data})

# Add new movie to rhe list
def add_movie(req):
    if req.method=="POST":
        name=req.POST.get('name')
        title=req.POST.get('title')
        year=req.POST.get('year')
        img=req.FILES['poster']
        try:   
            data=Details(name=name,title=title,year=year,img=img)
            data.save()
            return redirect('/')
        except :
            return redirect('register')
    return render(req,"register.html")

# Edit existing movie details
def update(req,id):
    movie=Details.objects.get(id=id)
    if req.method=="POST":
        i=edit_form(req.POST or None,req.FILES,instance=movie)
        if i.is_valid():
            i.save()
            return redirect('/')
    else:
        i=edit_form(instance=movie)
    return render(req,"edit.html",{'data':i,'movie':movie})

# Delete Movie from the list
def delete_me(req,id):
    if req.method=="POST":
        try:
            get_data=Details.objects.get(id=id)
            get_data.delete()
            return redirect('/')
        except:
            return redirect('/')
    return render(req,'delete.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movies</title>
    <link rel="stylesheet" href="{% static 'bs/bootstrap.min.css'%}">
    <script src="{% static 'bs/bootstrap.min.js'%}"></script>
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>

<body class="bg-info">
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <img src="{%static 'img/m.png' %}" class="d-inline-block align-text-top" width="50px" alt="">
            <a href="/" class="nav-link text-white display-4">Movie Store</a>
            <button class="navbar-toggler" type="button" data-bs-target="#navcontent" data-bs-toggle="collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navcontent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a href="#" class="nav-link fs-4 active">About</a>
                    </li>
                    <li class="nav-item">
                        <a href="/register" class="nav-link fs-4 active">Register</a>
                    </li>
                </ul>
            </div>
        </div>

    </nav>
    {%for i in messages%}
    {{i}}
    {%endfor%}
    {% block content %}
    {% endblock %}
    <footer class="footer text-center py-2 fixed-bottom bg-transparent">
        Image may subjected to &copy;  
    </footer>
    <script src="{% static 'bs/jquery.min.js' %}"></script>
</body>
</html>

templates/delete.html
{% extends 'details.html' %}
{% block style %}
.content{
padding:100px;
margin-top:100px;
}
{% endblock%}
{% block content%}
<div class="container">
    <div class="content d-flex justify-content-center">
        <div class="text-center bg-light row">
            <span>Are you sure you wants to delete this entry</span>
            <div class="col-sm-6 my-3">
                <form method="POST" class="form">
                    {% csrf_token%}
                    <input type="submit" class="btn btn-danger" value="Yes">
                </form>
            </div>
            <div class=" col-sm-6 my-3 ">
                <a href="/"><button class="btn btn-primary">No</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block style %}
.content{
margin-top: 100px;
}

{% endblock %}
</head>
{% block content %}
<header class="bg-light py-3">
    <span class="display-4">#{{data.name}}</span>
</header>
<div class="container ">
    <div class="content bg-light row">
        <div class="col-sm-6">
            <div class="row  py-5 border">
                <div class="col-sm">Movie Name:</div>
                <div class="col-sm fw-bold">{{data.name}}</div>
            </div>
            <div class="row py-5  border">
                <div class="col-sm">Movie Description:</div>
                <div class="col-sm  fw-bold">{{data.title}}</div>
            </div>
            <div class="row py-5  border ">
                <div class="col-sm">Release:</div>
                <div class="col-sm fw-bold">{{data.year}}</div>
            </div>
            <div class="row py-5  border ">
                <div class="col-sm">Action:</div>
                <div class="col-sm fw-bold">
                    {% block delete %}
                    <a href="{% url 'module1:edit' data.id%}"><button class="btn btn-warning">EDIT</button></a>
                   <a href="{% url 'module1:delete' data.id%}" class="mx-3"><button class="btn btn-danger">DELETE</button></a>
                    {% endblock %}
                </div>
            </div>
        </div>
        <div class="col-sm-6 text-center py-5 bg-danger">
            <img src="{{data.img.url}}" class="img-fluid img-thumbnail" style="height: 450px;" alt="">
        </div>
    </div>

</div>
{% endblock %}

templates/edit.html
{% extends "base.html" %}
{%block style%}
{%endblock%}
{%block content%}
<div class="container">
    <form action="{% url 'module1:edit' movie.id%}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="row gx-5 my-2">
            {{data.name.error}}
            <label for="name" class="col-sm-2  col-form-label">{{data.name.label}}</label>
            <div class="col-sm-8">
                {{data.name}}
                <span class="text-white">{{data.name.errors}}</span>
            </div>
        </div>
        <div class="row gx-5 my-2">
            <label for="name" class="col-sm-2  col-form-label">{{data.title.label}}</label>
            <div class="col-sm-8">
                {{data.title}}
                <span class="text-white">{{data.title.errors}}</span>
            </div>
        </div>
        <div class="row gx-5 my-2">
            <label for="name" class="col-sm-2  col-form-label">{{data.year.label}}</label>
            <div class="col-sm-8">
                {{data.year}}
                <span class="text-white">{{data.year.errors}}</span>
            </div>
        </div>
        <div class="row gx-5 my-2">
            <label for="name" class="col-sm-2  col-form-label">Poster</label>
            <div class="col-sm-8">
                {{data.img}}
                <span class="text-white">{{data.img.errors}}</span>
            </div>
        </div>
        <div class="d-flex my-5 justify-content-center">
            <input type="submit" value="Change" class="btn btn-primary">
        </div> 
    </form>
</div>
{%endblock%}

templates/home.html
{% extends 'base.html' %}
{% block style %}
        table{
            margin-top: 100px;
        }
{% endblock %}
{% block content %}
    <div class="container table-responsive">
        <table class="table  table-light table-hover">
            <caption class="px-4 bg-dark text-white">Movie List</caption>
            <thead class="table-dark text-center">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="">Title</th>
                    <th scope="col">Year</th>
                    <th scope="col">Poster</th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for i in data %}
                <tr>
                    <th scope="row">{{i.id}}</th>
                    <td><a href="{% url 'module1:search' i.id%}" class="nav-link text-primary">{{i.name}}</a></td>
                    <td> {{i.title}} </td>
                    <td> {{i.year}} </td>
                    <td><img src="{{i.img.url}}" class="img-fluid"  width="100px"></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
 {% endblock %}

templates/register.html
{% extends "base.html" %}
{% block style %}
.content{
    margin-top:100px;
    padding:100px;
}
{% endblock %}
{% block content %}

<div class="super_div">
    <div class="container">
        <div class="content bg-light">
            <legend><span class="text-primary text-capitalize fs-2 ">Add new movie</span></legend>
            <form action="register" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row gx-5 my-2">
                    <label for="name" class="col-sm-2  col-form-label">Movie Name:</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" name="name" placeholder="Movie name">
                    </div>
                </div>
                <div class="row gx-5 my-2">
                    <label for="name" class="col-sm-2  col-form-label">Movie Title:</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" name="title" placeholder="Movie Title">
                    </div>
                </div>
                <div class="row gx-5 my-2">
                    <label for="name" class="col-sm-2  col-form-label">Release:</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" name="year" maxlength="4" placeholder="Year of release">
                    </div>
                </div>
                <div class="row gx-5 my-2">
                    <label for="name" class="col-sm-2  col-form-label">Poster:</label>
                    <div class="col-sm-8">
                        <input type="file" class="form-control" name="poster" placeholder="Poster of movie">
                    </div>
                </div>
                <div class="d-flex my-5 justify-content-center">
                    <input type="submit" value="Register" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}